Snow Wizard Sample
pnp/copilot-pro-dev-samples pull request #8
Opened 2024-10-11 21:02 UTC by cristianoag

This sample project demonstrates an implementation of an M365 Declarative Copilot that interfaces with ServiceNow to list and create incidents.

2024-10-15 15:16 UTC, waldekmastykarz requested changes
Cool! Let's do a few adjustments before we merge it. Also, would you be willing to add a sample.json file in the assets folder next to images? This will make your sample appear in the sample gallery at https://adoption.microsoft.com/en-us/sample-solution-gallery/?keyword=&sort-by=updateDateTime-true&page=1&product=Microsoft+365+Copilot. Here's a template that you can use: https://github.com/pnp/copilot-pro-dev-samples/blob/main/templates/sample-template.json. Check out other samples to see how it looks like in practice.

2024-10-15 15:16 UTC, waldekmastykarz commented on samples/da-SnowWizard/SnowWizard/env/.env.dev
> +# This file includes environment variables that will be committed to git by default.
Let's add .env.local as well so that folks can run the sample locally by pressing F5. You could use the following contents:

```text
TEAMSFX_ENV=local
APP_NAME_SUFFIX=local
```

2024-10-15 15:16 UTC, waldekmastykarz commented on samples/da-SnowWizard/SnowWizard/teamsapp.local.yml
> +  # Creates a Teams app
Let's include the following snippet to create local.settings.json. Otherwise, running Azure Functions will fail:

```yaml
  - uses: file/createOrUpdateJsonFile
    with:
      target: ./local.settings.json
      content:
        IsEncrypted: false
        Values:
          FUNCTIONS_WORKER_RUNTIME: 'node'
```

2024-10-17 16:49 UTC, cristianoag commented on samples/da-SnowWizard/SnowWizard/env/.env.dev
> +# This file includes environment variables that will be committed to git by default.
I have a .env.local file on my end, which contains data from my development tenant. The default .gitignore for TeamsFX excludes this file (along with others) from being pushed. I'll create and push a new version that includes only the necessary two lines.

2024-10-17 16:52 UTC, cristianoag commented on samples/da-SnowWizard/SnowWizard/teamsapp.local.yml
> +  # Creates a Teams app
Again I have that file on my end, but it is excluded by the default by the .gitignore generated by the Teams Toolkit. I'll comment out the relevant line in the .gitignore and push the changes. This will include the updated .gitignore along with the two files you need.

2024-10-17 17:09 UTC, cristianoag commented
Done. PR updated with all the changes requested.

2024-10-18 07:25 UTC, waldekmastykarz commented on samples/da-SnowWizard/SnowWizard/teamsapp.local.yml
> +  # Creates a Teams app
We exclude the default from source control by default, because it might contain secrets. Using the lines I shared above is a safe way to create the file if necessary so that the project runs flawlessly.

2024-10-18 07:26 UTC, waldekmastykarz approved these changes

2024-10-18 07:26 UTC, merged

2024-10-29 01:34 UTC, PopWarner commented
🎉✨ Woohoo! ✨🎉

Thank you @cristianoag for your awesome contribution to the community with this merged PR! 🚀 You've earned a Credly badge through the Microsoft 365 & Power Platform Recognition Program. 🏅 To receive your badge, please take a moment to opt in to the program. You can learn more and sign up here: https://aka.ms/community/recognition.

Can't wait to see you in the program! 🎊

Thanks,
David Warner 🧡💜

cc: @waldekmastykarz